import a from './a.jpg';
import logo from './logo.jpeg';
import a1 from './a1.png';
import a2 from './a2.png';
import a3 from './a3.png';
import a4 from './a4.png';
import a5 from './a5.png';
import a6 from './a6.png';
import a7 from './a7.png';
import a8 from './a8.png';
import a9 from './a9.png';
import a10 from './a10.png';
import a11 from './a11.png';
import a12 from './a12.png';
import a13 from './a13.png';
import a14 from './a14.png';
import a15 from './a15.jpeg';
import pencil from './pencil.jpeg';
import sketch from './sketch.jpeg';
import board from './board.webp';
import table from './table.webp';
import timeline from './timeline.webp'
import calendar from './calendar.webp'
import list from './list.webp'
import gallery from './gallery.webp'
import customizeinfo from './customize-info.webp'
import buildanypage from './build-any-page-communicate-any-idea.webp'
import matchGrup from './match-group.webp'
import avatars from './avatars.webp';
import welcomeNotion from './welcome-to-notion.webp'
import communityIcon from './community-icons-V2.webp'
import deborah from './twitter-avatar-deborah.avif'
import andre from './twitter-avatar-andre.png'
import oliver from './twitter-avatar-oliver.png'

export { a, logo, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, pencil, sketch, board, list, gallery, table, timeline, calendar, customizeinfo, buildanypage, matchGrup, avatars, communityIcon, welcomeNotion, andre, oliver, deborah }